name: ubuntu CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        mkdir build-ubuntu
        cd build-ubuntu
        cmake ..
        make
    - name: movefile
      run: |
        mkdir -p ./ubuntu
        ls -ltr ./build-ubuntu/IBJts/samples/Cpp/TestCppClient
        mv ./build-ubuntu/IBJts/samples/Cpp/TestCppClient/TestCppClient ./ubuntu/TestCppClient
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: ./ubuntu
